name: OLBCI_PUSH_MASTER

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # Runs a single command using the runners shell
      - name: Run playwright
        run: npm run env:test
      - name: Move Playwright report to D:\Reports\Playwright
        run: |
          # Make sure destination folder exists
          if (-Not (Test-Path "D:\Reports\Playwright")) {
            New-Item -Path "D:\Reports\Playwright" -ItemType Directory -Force
          }
      
          # Move the report folder
          Move-Item -Path "${{ github.workspace }}\playwright-report" -Destination "D:\Reports\Playwright" -Force
        shell: pwsh
